### ISSUE TITLE
Basic support for OpenApi tags

### ISSUE THREAD

**Issue by krzemin** [julienrf/endpoints#105]
It'd be really nice if endpoints could support grouping operations by tags in OpenApi documentation, as in the example here: https://swagger.io/docs/specification/grouping-operations-with-tags/

I think it's sufficient to annotate operations only with optional tag list (empty by default). Providing more detailed tag description on root level would be also nice, but not necessarily in scope of this ticket.

After quick investigation, I think it may be quite simple to implement, although IMHO it requires modifying `endpoint` signature to:

```scala
def endpoint[A, B](
    request: Request[A],
    response: Response[B],
    summary: Documentation = None,
    description: Documentation = None,
    tags: List[String] = Nil
  ): Endpoint[A, B]
```

Are you OK to go this way?

**Comment by Krever** [comment]
For me its ok. OpenAPI is more or less a standard for describing endpoints so aligning our API with it seems reasonable, as long as optional parts can be ommited.
