### ISSUE TITLE
Crossbuild for scala 2.13

### ISSUE THREAD

**Issue by Krever** [julienrf/endpoints#112]
As M5 is already there, let's see if we can publish at least core algebra for Scala 2.13

**Comment by pjazdzewski1990** [comment]
I'm taking this one for SW Spree

**Comment by Krever** [comment]
The first step were done by @pjazdzewski1990 . Lets keep this issue open until all the dependencies become available and we can migrate fully.

**Comment by julienrf** [comment]
Update: 2.13.x is already supported by the algebra. To upgrade the interpreters we need the corresponding libraries (play, akka, sttp, etc.) to be published for 2.13.0. A work in progress is available in #279. Help is welcome!

**Comment by fabianpage** [comment]
scala-collection-compat is not jet released for 2.13.0

**Comment by fabianpage** [comment]
play-json depends on macro-compat which is not yet release: https://github.com/playframework/play-json/pull/281

**Comment by rgugliel** [comment]
Hey!
It seems that a version of play-json that supports 2.13 (2.8.0-M3) has been published. 

Is it possible to move forward? Is there something I can do to help?

**Comment by julienrf** [comment]
Hello! An easy way to help would be to bump the Scala version number to `2.13.0` in the #279 branch and let the CI tell us which dependencies are missing ;)

**Comment by rgugliel** [comment]
So, the situation is a bit messy.
Here is a chain of dependencies that prevents the use of Scala 2.13.0 if I'm not mistaken:
Endpoint -> akka-http-circe -> avro4js -> Magnolia stuff

Master branch of the last one (https://github.com/propensive/magnolia) does not even compile on my machine. Tried to open a PR for one of their deps. Will see.

**Comment by julienrf** [comment]
I’ve just updated the #279 PR. The only Circe version that supports 2.13.0 has dropped support for 2.11, and depends on a milestone release of Cats. We should wait a little bit more that these milestone releases become final releases. Additionally, there are a lot of “eviction” warnings that should be investigated.

**Comment by rgugliel** [comment]
Ok, thanks for the update!

**Comment by julienrf** [comment]
Cats 2.0.0 has been released! https://twitter.com/kailuowang/status/1171251214371237891

**Comment by julienrf** [comment]
We are blocked by hseeberger/akka-http-json#325

**Comment by julienrf** [comment]
Closed by #279
