### ISSUE TITLE
Unspecified behavior of `optField` in JSON schemas

### ISSUE THREAD

**Issue by stefanholzmueller** [julienrf/endpoints#123]
Basically, it is not specified in the JSON schema algebra if `optField` means "may be absent" or "may have null value". The circe interpreter encodes `None` as `null` while the Play JSON interpreter (#122) does not write the field in case of `None`.

I briefly discussed this with @julienrf in #122, the relevant correspondence is here:

> > I realize that the name optField might be misleading since it suggests that the field can be absent. In practice, the current circe encoder implementation always emits optional fields, giving them the null JSON value for the None Scala value. But I don’t remember if there is a good reason for having that behavior rather than not emitting the field, actually…

> Right now, the behavior is just unspecified. We could...
a) document the inconsistency at least.
b) specify that either the circe or Play JSON behavior is "correct", and fix the other one.
c) define optField as "mandatory field with null value allowed, which is mapped to Option". Then add a new method to the schema algebra that means "field that exists or is absent, mapped to Option".
In some rare cases both meanings actually make a difference, e.g. with partial updates (PATCH requests): I think there is the distinction between "set this value to null" and "leave the value as-is".
This topic might be worth some research, I'd rather not do it as part of this PR.

Right, a present field with the null value could mean Some(None), whereas an absent field would just mean None. This is something that we could work on later.

**Comment by stefanholzmueller** [comment]
Idea: add the following to the algebra:
```scala
/** basically `optField`, but with clear semantics: `None` means the field is absent */
def optionalField[A](name: String, documentation: Option[String] = None)(implicit tpe: JsonSchema[A]): Record[Option[A]]

/** maps `null` JSON values to Scala `None` */
implicit def nullJsonSchema[A](implicit jsonSchema: JsonSchema[A]): JsonSchema[Option[A]]
```

So `field[String]` means the field is mandatory and contains a non-null string,
`field[Option[String]]` means the field is mandatory and contains a nullable string,
`optionalField[String]` means the field can be absent, but if it's there, it contains a non-null string,
`optionalField[Option[String]]` means the field can be absent, and the value can be null (returning a nested `Option[Option[A]]`).

Not sure what to do with the existing `optField`; we might mark it as deprecated, or just keep it as "I don't care" convenience method.

Have not really tried it yet, because I want to hear some feedback first.

**Comment by Krever** [comment]
For me it makes sense. About `optField`: let's drop it completely or use the name for what you defined as `optionalField` ;)

**Comment by julienrf** [comment]
I agree about the expected behavior of `optField`/`optionalField`.

I’m not sure about `nullableJsonSchema`. It would allow the construction of inconsistent programs:

~~~ scala
val schema: JsonSchema[Option[Option[Int]]] = nullableJsonSchema(nullableJsonSchema[Int])

// Using the schema to encode Some(None)…
val someNoneJson = schema.encode(Some(None))
// Some(None) is modeled by the JSON `null` value
someNoneJson == Json.Null

// But, when decoding someNoneJson…
val decoded: Option[Option[Int]] = schema.decode(someNoneJson)
// then we would get None!
decoded == None
~~~

Unless I’m missing something?

**Comment by stefanholzmueller** [comment]
@julienrf I think you are right, I have not thought about "nesting" `nullableJsonSchema`, and arguably that would be a misuse of the API. Yeah, I'd rather make it impossible to construct nonsensical cases like this, I just have no good idea how to achieve it.

One intuition would be to leverage the type system with something like `type Nullable[A] <: JsonSchema[A]` but even thinking about it hurts my brain.

Another idea would be to have distinct methods in the algebra for all four cases:
`field[String]` means the field is mandatory and contains a non-null string,
`nullableField[String]` means the field is mandatory and contains a nullable string,
`optionalField[String]` means the field can be absent, but if it's there, it contains a non-null string,
`optionalNullableField[String]` (ugh!) means the field can be absent, and the value can be null.

It just seems to me that optional/mandatory **fields** and nullable/non-null **values** should be orthogonal and composable. Still waiting for the stroke of genius.

**Comment by Krever** [comment]
> I don’t think we need nullableField at all.

I have to disagree. I use nulls in json much more frequently than missing fields. I find missing fields just too vague. If the field is present I at least know that the other side knows about its existence and null indicates a lack of value. Using missing fields to indicate optional values may mean two completely different things: the other side is in some old version and doesnt know about this field or it knows about it but the value is missing.

Or maybe I just misunderstood sth?

**Comment by julienrf** [comment]
> I use nulls in json much more frequently than missing fields.

Oh, OK, that’s not what I thought.

That being said, I’m not sure using a `null` value provides more benefits than omitting the field, does it?

In any case, my point is that if we want to properly represent optional values (mapped to `Option[A]`), we have to have an explicit representation of at least `Some(None)`, `Some(Some(None))`, `Some(Some(Some(None)))`, etc.

**Comment by stefanholzmueller** [comment]
@julienrf can you give an example or use case for `Some(Some(None))`? I cannot imagine having more than two "layers" of `Option`: one for optional/mandatory fields and one for nullable/non-null values.

> I don’t think we need nullableField at all.

This confuses me. Do we agree that we need to distinguish the four cases I mentioned above? Are you talking about representing nullability in a different way than with `nullableField`?

**Comment by julienrf** [comment]
I don't have an idea of use for three layers of options off the top of my head, but if the algebra makes it possible to build JSON schemas for such types, then they should be consistently encoded and decoded, which requires a representation of Some(None) for arbitrary levels of Some. 

About nullableField, sorry I was not clear. I do agree that the use case makes sense, but I'm not sure we should use null for that.

**Comment by stefanholzmueller** [comment]
Then maybe the most pragmatic approach is to use explicit methods for those four cases and drop `nullableJsonSchema`?

```scala
// parameter lists omitted for brevity
def field[A]: Record[A] // mandatory field with non-null value
def nullableField[A]: Record[Option[A]] // mandatory field with nullable value
def optionalField[A]: Record[Option[A]] // optional field with non-null value
def optionalNullableField[A]: Record[Option[Option[A]] // optional field with nullable value
```
I have to admit, the last one looks ugly, because you have to interpret the nested `Option`s: the "outer" one means the field exists or not, the "inner" one means the value is non-null or JSON `null`.

At least this approach would not allow for arbitrary nesting of `Option`, I think.
