### ISSUE TITLE
Support for `format` property of OpenAPI primitive types

### ISSUE THREAD

**Issue by guersam** [julienrf/endpoints#132]
OpenAPI specifies `format` property in addition to `type` [1]. There are a few primitive types such as date or dateTime that have different `format`s, with the same `string` type.

It would be nice to add additional `format: Option[String]` member to `endpoints.openapi.model.Schema.Primitive` so that we can increase openapi spec coverage.

[1] https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types

**Comment by julienrf** [comment]
Fixed by #136
