### ISSUE TITLE
Shorter derived schema tag name in OpenAPI

### ISSUE THREAD

**Issue by guersam** [julienrf/endpoints#137]
`endpoints.openapi.JsonSchemas` uses the fully qualified class name as the tag of a derived json schema. Unfortunately many openapi client generators doesn't support for package stripping, so that the generated models tend to have unnecessarily long class names such as `ComExampleMyApiProtocolRealClassName` from `com.example.my.api.protocol.RealClasssName`.

Suggestions:
  1. Use simple name instead of FQCN
  2. Let users choose between simple name and FQCN via
      a. an additional argument of `genericJsonSchema`
      b. implicit `Configuration` class like [circe-generic-extras](https://circe.github.io/circe/codecs/custom-codecs.html#custom-key-mappings-via-annotations)
  3. Use FQCN by default and let users specify the prefix to strip via something like `openapi.JsonSchema#packageNameToStrip`

**Comment by Krever** [comment]
> Let users choose between simple name and FQCN via
a. an additional argument of genericJsonSchema
b. implicit Configuration class like circe-generic-extras

This could also be an overridable method in the interpreter. I'm not big fan of those but it is the least intrusive...

**Comment by Krever** [comment]
I was thinking about `e.o.JsonSchema#tagName: ClassTagring => String` but iether case its the same idea :)

**Comment by guersam** [comment]
Thinking more about it, just realized that we have to embed `ClassTag` in json algebra to support `ClassTag => String`, because the generic derivation happens out of the openapi interpreter :( Maybe `String => String` has more reasonable price.

**Comment by krzemin** [comment]
I encountered the same problem. I temporarily solved it in my project my just renaming every derived schema by a following macro

```scala
object JsonSchemaAutoNamed {

  def autoNamedImpl[S[_], T: c.WeakTypeTag](c: blackbox.Context)(jsonSchema: c.Expr[S[T]]): c.Expr[S[T]] = {
    import c.universe._
    val name = determineName(weakTypeOf[T].typeSymbol.fullName)
    c.Expr[S[T]](q"named($jsonSchema, $name)")
  }

  private def determineName(fullName: String): String = {
    fullName.split('.').dropWhile(_.head.isLower).mkString
  }
}

trait JsonSchemaAutoNamed { self: _root_.endpoints.algebra.JsonSchemas =>

  def autoNamed[S[X] <: JsonSchema[X], T](jsonSchema: S[T]): S[T] =
    macro JsonSchemaAutoNamed.autoNamedImpl[S, T]
}
```

then in use site I have to compose in `JsonSchemaAutoNamed` and:

```scala
implicit def fooSchema: JsonSchema[Foo] = autoNamed(genericJsonSchema[Foo])
```

Note that `determineName` works quite nice with definitions (even multiply) nested in companion objects. For example `io.a.b.c.Foo.Bar.Baz` is auto re-named to `FooBarBaz`.  

I would definitely like to see dedicated support for naming schemes in the core algebra (`ClassTag => String` sounds nice). Also, providing few ready to use functions that support different naming styles (FQN, classname only, etc.) would be really appreciated.

**Comment by guersam** [comment]
To proceed even further, simple `ClassTag` is not enough because OAS3 doesn't support for generic 
schema such as `MyResponse<A>`, so that when there are two or more type application all schema names will be just `MyResponse`.

Extracting applied type parameters will probably involve macro, and the result could be something like `NonEmptyList[ClassTag] => A`, `(TypeTag, List[TypeTag]) => A` or something similar so that I'm not sure if it's worth it to have half powered `ClassTag => String` in the core algebra.

**Comment by guersam** [comment]
BTW your workaround looks nice! I brutally copy & pasted whole `generic.JsonSchemas` and just did whatever I want...

**Comment by krzemin** [comment]
> To proceed even further, simple ClassTag is not enough because OAS3 doesn't support for generic
schema such as MyResponse<A>, so that when there are two or more type application all schema names will be just MyResponse

I'm not sure if using generics at the API layer is the best practice as many other languages don't support them. OTOH generics might be used as templates to instantiate concrete data types in the API.

Currently, in generic derivation names are generated from `ClassTag`s, so there is no out-of-the box support for generics. Users still can do renaming by using `named` after JsonSchema was derived.

> Extracting applied type parameters will probably involve macro, and the result could be something like NonEmptyList[ClassTag] => A, (TypeTag, List[TypeTag]) => A or something similar so that I'm not sure if it's worth it to have half powered ClassTag => String in the core algebra.

Note that support for applied generics might be achieved simply by `TypeTag => String` as having `tt: TypeTag` you can access all the type arguments via `tt.tpe.typeArgs`. Macro workaround can be easily extended to support generics.

**Comment by guersam** [comment]
> generics might be used as templates to instantiate concrete data types in the API.

Yes, that's what I want :) It would be enough if `FooBarBaz` or `Foo_Bar_Baz` can be derived from `Foo[Bar, Baz]`.

Two more things I want to discuss:
  1. `WeakTypeTag` or `TypeTag`?
        
        `TypeTag` has stronger guarantee than `WeakTypeTag` has that all type references are concrete, so that I'd prefer `TypeTag` if possible. Do we have any usecase that `WeakTypeTag` is needed instead?
  
  2. Which module to add `autoNamed`?
       
        Adding `autoNamed` to the core algebra introduces scala-reflect dependency to `json-schema` that has no other dependencies yet. If you don't mind I'd prefer adding it to `json-schema-generic` to keep `json-schema` pure.

**Comment by krzemin** [comment]
1. I guess `TypeTag` as at the API level only fully instantiated types make sense. 

2. Correct. Currently automatic names are given by generic schema derivation. I think this would be the right place to implement such customization.

**Comment by krzemin** [comment]
Just realized that `TypeTag` approach might be problematic for Scala.js as its runtime doesn't have TT. So in order to support naming generics, we would need to come up with some own representation that we capture from compile-time TT or just provide few pre-defined naming styles without possibility to plug the user function in.

**Comment by kirankbs** [comment]
Few of my endpoints have a response like Page[T] or Page[Response[T]] etc. I tried both the approaches overridable method at interpreter or using macros above. 
It was failing at some places due to one of the implicit resolutions is using `nameSchema` at `e.g.JsonSchemas.GenericJsonSchemaLowLowPriority#recordGeneric`. 

I am forced to copy paste e.g.JsonSchemas and added the below simple reflection based solution to it and it is working fine for sum, product and any kind to kind level.
	
Test Case			|		Output
:---------:		|		:------:
Bar					|		Bar
Foo[Bar]			|		Foo.Bar
Qux[Bar, Baz]		|		Qux.Bar.Baz
Quuz[Foo[Bar]]	|		Quuz.Foo.Bar

```
  def uniqueNameSchema[A: WeakTypeTag, S[T] <: JsonSchema[T]](schema: S[A]): S[A] = {

    val determineName: String => String = _.split('.').dropWhile(_.head.isLower).mkString(".")

    val lastName: String => String = _.split('.').last

    def loop(t: Type, acc: List[String]): List[String] = {

      if (t.typeArgs.isEmpty) {
        val childName = lastName(t.typeSymbol.fullName)
        acc :+ childName
      } else {
        val parentName = lastName(t.typeSymbol.fullName)
        t.typeArgs.flatMap(t1 => loop(t1, acc :+ parentName))
      }

    }

    val uniqueName = (determineName(weakTypeOf[A].typeSymbol.fullName) ::
      weakTypeOf[A].typeArgs.flatMap(t => loop(t, List.empty[String]))) mkString (".")

    named(schema, uniqueName)
  }
```

Use above method at three places:
1. genericJsonSchema
2. e.g.JsonSchemas. e.g.JsonSchemas.GenericJsonSchemaLowLowPriority#recordGeneric
3. e.g.JsonSchemas. e.g.JsonSchemas.GenericJsonSchemaLowLowPriority#taggedGeneric

I would really like to have this in json-schema-generic module. I am ready to contribute to this if we want this.

**Comment by julienrf** [comment]
I’m afraid `WeakTypeTag` doesn’t work on Scala.js. We could implement a macro that would surface the type information to the runtime. But then we need a way to configure the generic derivation to pick one strategy to turn the type information into a `String` type tag.

First, see if #318 solves your problem (see also #315 for more discussion points).

If #318 doesn’t work for you, an alternative approach would be to introduce an annotation that would allow users to specify a name. Like what has been proposed in #128, but for type tags. What do you think?

**Comment by kirankbs** [comment]
Got some time to check this. Below are my findings:

- @julienrf  You are right that `WeakTypeTag` is not working with scala.js and introducing runtime reflection on json-generic is not a good idea.
- #318 or annotation-based solution will not work for any entity having another generic derivation inside. It is user discipline to add `namedGenericJsonSchema` for inner entity too and leads to more laborious work.
- `namedGenericJsonSchema` is not working for CoProducts. 
- If the user misses writing `namedGenericJsonSchema` for any F[_] at any kind level then the compiler does not warn you for the documentation mess going to happen.

So, I am still using `WeakTypeTag` solution internally in my codebase but I am trying to address this problem at library level as many `json-generic` users may need this feature.

While addressing this problem at the library level, I will check both approaches 
1. Macro suggestion
2. reflection `Manifest`

**Comment by julienrf** [comment]
Thanks @kirankbs for sharing your findings!

I would suggest also to have a look at https://github.com/scalalandio/endpoints-json-schemas-macros, which uses a macro-based derivation system.

I’m currently considering the addition of two annotations in endpoints-json-schemas-generic to customize (1) tag names and (2) descriptions (see #128 and #249), although, as you noticed, this requires annotating all the classes (there is no global derivation configuration).

**Comment by julienrf** [comment]
FYI, in #393 the `classTagToSchemaName` method is public, and can be overridden to use a short name rather than the fully qualified class name.
