### ISSUE TITLE
Rename the `option` response combinator to `wheneverFound`

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#140]
404 response status codes are actually handled by the `option` response combinator, that turns a `Response[A]` into a `Response[Option[A]]` (`None` being mapped to a 404 response).

However, the `Option` type can be used for other means, in responses (for instance, we also use it for authenticated endpoints, to mean that the request was not authenticated).

I think that we should rename the `option` combinator to `wheneverFound`, so that it conveys better its meaning:

~~~ scala
// currently
val userById =
  endpoint(get(path / "user" / segment[Long]), option(jsonResponse[User]()))

// with the proposed change
val userById =
  endpoint(get(path / "user" / segment[Long]), wheneverFound(jsonResponse[User]()))
~~~

**Comment by Krever** [comment]
Im not sure about the naming, but can think about anything better, other than postfix syntax `jsonResponse[User]().orNotFound`
