### ISSUE TITLE
Macro-based generic JsonSchema derivation

### ISSUE THREAD

**Issue by krzemin** [julienrf/endpoints#144]
Currently in `json-schema-generic` derivation of JsonSchema typeclass for arbitrary user-defined types is implemented with shapeless-based generic typeclass derivation. I'm considering crafting another implementation that would be purely macro-based.

Advantages?
- immediate compilation-time performance improvements by default for all users (2.11-2.13), especially if we use only blackbox macros
- no runtime overhead as materialization to HList/Coproduct would not be required
- more descriptive error messages (than `@implicitNotFound`)
- no dependency on shapeless required any more

Such new implementation should perhaps support:
- `@documentation` annotation implemented in #128, both for product fields and coproduct instances
- different naming conventions, as discussed in #137

**Comment by guersam** [comment]
How about magnolia? https://propensive.com/opensource/magnolia/

**Comment by Krever** [comment]
My experience with magnolia is very positive. If it's possible to get what we need with it, then I'm 100% in favor. The implementation tends to much much simpler than with shapeless.

**Comment by krzemin** [comment]
I tried prototyping derivation with Magnolia before creating this ticket. It turned out that there is one problematic case (optional fields with `optField`) where having a field of type `Option[T]` we require a type class instance for `T`, but using current magnolia it's not possible to request it.

**Comment by krzemin** [comment]
Closing, as I have released json schemas macros as separate contrib project: https://github.com/scalalandio/endpoints-json-schemas-macros
