### ISSUE TITLE
Make the JSON decoders agnostic

### ISSUE THREAD

**Issue by mdedetrich** [julienrf/endpoints#16]
Would be fantastic if endpoints had the ability to use different JSON backends (and not just circe), i.e. using play-json or another JSON library

**Comment by julienrf** [comment]
That’s actually the case, there is a `[JsonEntitiesAlg](https://github.com/julienrf/endpoints/blob/master/algebra/src/main/scala/endpoints/JsonEntitiesAlg.scala)` module that is backend agnostic.

There is currently only one implementation of this module, [`CirceCodecs`](https://github.com/julienrf/endpoints/blob/master/algebra-circe/src/main/scala/endpoints/CirceCodecs.scala), which happens to be using circe, but it would be very simple to have another implementation based on play-json:

~~~ scala
trait PlayCodecs extends JsonEntitiesAlg {
  import play.api.libs.json.Format

  type JsonResponse[A] = Format[A]
  type JsonRequest[A] = Format[A]

}
~~~

**Comment by julienrf** [comment]
Can I close this issue?

**Comment by mdedetrich** [comment]
Yes, apologies for not responding earlier
