### ISSUE TITLE
Support other enumeration encoding types than String

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#185]
The current signature for defining an enumeration schema only works with `String` for the encoded type:

https://github.com/julienrf/endpoints/blob/9805cb1ba1a712cd514f284fb2c14e5316656403/json-schema/json-schema/src/main/scala/endpoints/algebra/JsonSchemas.scala#L82

It should be possible to support an arbitrary encoded type `E`, provided a given `JsonSchema[E]`:

~~~ scala
def enumeration[A, E](values: Seq[A])(encode: A => E)(implicit tpe: JsonSchema[E]): Enum[A]
~~~

**Comment by russellporter** [comment]
I'm trying to implement this :)

**Comment by julienrf** [comment]
So, this issue has the problem as #121: we need to include an actual JSON codec in the OpenApi interpreter.
