### ISSUE TITLE
[QUESTION] Using this library with akka-http ?

### ISSUE THREAD

**Issue by hajime-moto** [julienrf/endpoints#23]
Just wondering if there are plans to add support for akka-http ?

**Comment by julienrf** [comment]
At the moment I don’t plan to take time to do that, but that would be a nice solution to #15. Would you be interested in contributing an akka-http interpreter? I can help you a bit in this work :)

**Comment by hajime-moto** [comment]
I haven't coded in years so I don't think I will be much help here :( .. But I going to ask one of my developers to contribute. Are there any guidelines on how the interpreter should be written or should we just reference the code for Play ?

**Comment by julienrf** [comment]
I would more than warmly welcome such a contribution!

Currently the project is more in the form of an experiment, so there is not much documentation. I’m working to gradually improve the situation :)

Yes, drawing inspiration from the PlayRouting and PlayClient interpreters is a good idea. I can also give help on gitter: https://gitter.im/julienrf/endpoints

**Comment by ngbinh** [comment]
@julienrf this library looks quite interesting to me. I can probably take shot at this issue.

**Comment by julienrf** [comment]
Great! Le me know if you need any additional information.
