### ISSUE TITLE
Support binding query string parameters to a list of values

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#237]
The `qs` (and `qsOpt`) method can create a `QueryString[A]`, but in some cases it is useful to produce a `QueryString[List[A]]`. We could do it in two ways:

Either by introducing a `qsList` method in `endpoints.algebra.Requests`:

~~~ scala
def qsList[A: QueryStringParam](name: String, docs: Option[String] = None): QueryString[List[A]]
~~~

And then an URL taking several query string parameters could be defined as follows:

~~~ scala
path / "foo" /? qsList[Int]("ids")
~~~

The second solution would be to introduce the following `listQueryStringParam` combinator in `endpoints.algebra.Requests`:

~~~ scala
implicit def listQueryStringParam[A: QueryStringParam]: QueryStringParam[List[A]]
~~~

This would allow users to define an URL taking several query string parameters as follows:

~~~ scala
path / "foo" /? qs[List[Int]]("ids")
~~~

I think the second solution is preferable but it would require more changes in the way we implement interpreters.

**Comment by tdroxler** [comment]
+1 for this feature!

**Comment by julienrf** [comment]
Short update about this issue: I’ve started working on it (following the second solution presented in the issue description) but I’d like to use it as an opportunity to increase the coverage of our tests (we have almost no tests on URL encoding and decoding), and to improve the way we handle some failures. So, this is taking a bit longer than expected.

If you are blocked by this issue, my advice would be to implement, in your project, the first solution presented in the issue description.

**Comment by tdroxler** [comment]
Hi, not blocking for now, thx a lot for all you work.
