### ISSUE TITLE
Field descriptions via tagged types

### ISSUE THREAD

**Issue by jchapuis** [julienrf/endpoints#249]
Our documentation requirements include providing some descriptive text for each model field. We could use the JSON schema description DSL but that means introducing a separate schema: we would much rather use automatic generation with `genericJsonSchema`.

So how about taking advantage of tagged types and a dedicated typeclass allowing for providing descriptions for each tag?

For instance, with the following definitions using shapeless tagged types:

```scala
object tags {
  sealed trait CardNumber
  sealed trait CVV
}
import tags._
case class CreditCard(number: String @@ CardNumber, 
                      holder: String, 
                      cvv: String @@ CVV)
```

And a typeclass definition and instances: 

```scala
 trait TypeDescriptor {
    def apply(): String
  }

  implicit val cardNumberDescriptor: TypeDescriptor =  () => "Credit card number"
  implicit val cvvDescriptor: TypeDescriptor = () => "Card verification value"
```

With that in place, `genericJsonSchema` could grab instances of this typeclass for a type or tag and include the description in the generated schema. This also allows for reuse of descriptions btw.
Does it make sense?

**Comment by julienrf** [comment]
I’m in general not a fan of introducing such machinery and would rather write the schemas by hand. But there seems to be a demand for what you want (see also #128) so it is probably worth investigating! I have a preference for the annotation-based approach (implemented in #128). What do you think?

**Comment by julienrf** [comment]
Another approach might be to transform parts of a generically derived schema. For instance, something along these lines: https://jto.github.io/articles/alacarte_validation/

**Comment by jchapuis** [comment]
Cool, I had not seen that there was already a PR for this.

I agree, the annotation-based approach has the advantage of simplicity and it's very quick to document resource models as you go. It also has the advantage that a PR already exists 😉 as I am not sure I have the time right now to experiment on my idea. 

The downside is the use of annotations, which are not enriching the model types with more information, that could also be used for other aspects (validation, for instance). I can imagine that by having very richly typed resources, you can then use those types for razor-sharp validation in addition to the documentation aspects.

The posterior transformation approach is interesting, but IMO suffers from duplication as you have to identify each field by symbol or string, and also the documentation is provided in a separate place so it cannot also play the self-documenting role that annotations (or types) can provide.
