### ISSUE TITLE
OpenApi schema vs circe

### ISSUE THREAD

**Issue by goboss** [julienrf/endpoints#263]
Hi!

I really enjoy using your library, but there is one thing I might be misunderstanding.
Is there a way to use circe instead of `generic.JsonSchemas` to generate json schema for openapi?
It seems that with `circe.JsonSchemas` the generated documentation is missing the `components.schemas` part. The reason I'm stuck with circe is that I have a very complex model with lots of custom codecs that I need to use.

Here is a simplified example of my circe setup:
```scala
trait TestEndpoints
  extends algebra.Endpoints 
     with algebra.JsonSchemaEntities 
     with circe.JsonSchemas {
  
  val testEndpoint: Endpoint[MyModel, MyModel] =
    endpoint(
      post(path / "test", jsonRequest[MyModel]()),
      jsonResponse[MyModel]()
    )
  
  implicit val schema: JsonSchema[MyModel] = JsonSchema(MyModel.circeEncoder, MyModel.circeDecoder)
}

object TestEndpointsDocumentation 
  extends TestEndpoints 
     with openapi.Endpoints 
     with openapi.JsonSchemaEntities {

  val api: OpenApi =
    openApi(Info("Test", "0.0.1"))(testEndpoint)
}

object TestRoutes extends CounterEndpoints with OpenApiSchemas with JsonSchemaEntities {
  def docRoute: Route =
    endpoint(get(path / "documentation.json"), jsonResponse[OpenApi]())
      .implementedBy(_ => TestEndpointsDocumentation.api)
}
```

Thanks a lot! :)

**Comment by julienrf** [comment]
This is probably a bug, the circe `Encoder` produced by `JsonSchemaEntities` should emit the `components.schemas` part.

**Comment by julienrf** [comment]
Oh, I didn’t notice this line:

~~~ scala
implicit val schema: JsonSchema[MyModel] = JsonSchema(MyModel.circeEncoder, MyModel.circeDecoder)
~~~

This is not the right way of generating a `JsonSchema`, you should use the operations provided in the `algebra.JsonSchemas` trait, not the operations of that specific interpreter.

I am, by the way, surprised that you can mix `openapi.JsonSchemaEntities` into `TestEndpoints` (which already has `circe.JsonSchemas`) without getting a compilation error.

But, to answer better your request, it is not possible to generate a JSON schema from circe’s encoders and decoders, this is why the `components.schemas` section remains empty… Circe’s encoders and decoders are just functions, there is no way to “see” what they do and deduce the underlying schema.

The recommended approach is to do it the other way around: define your `JsonSchema[MyModel]` by using the operations provided in the algebra (or by using `generic.JsonSchemas`), and then derive the circe’s encoders and decoders from that.

What specifically is limiting you in `generic.JsonSchema` compared to circe’s derivation?

**Comment by goboss** [comment]
The `generic.JsonSchema` derivation has issues deriving my model. I have narrowed down the problem to `scala.Option`. For instance here is a slightly simplified version of the quick start example (notice `Option[Counter]`):
```scala
import akka.http.scaladsl.server.Route
import endpoints.openapi.model.OpenApiSchemas
import endpoints.{algebra, generic}

/**
  * Defines the HTTP endpoints description of a web service implementing a counter.
  * This web service has two endpoints: one for getting the current value of the counter,
  * and one for incrementing it.
  */
trait CounterEndpoints
  extends algebra.Endpoints
    with algebra.JsonSchemaEntities
    with generic.JsonSchemas {
  
  /**
    * Get the counter current value.
    * Uses the HTTP verb “GET” and URL path “/current-value”.
    * The response entity is a JSON document representing the counter value.
    */
  val currentValue: Endpoint[Unit, Option[Counter]] =
    endpoint(get(path / "current-value"), jsonResponse[Option[Counter]]())
  
  /**
    * Increments the counter value.
    * Uses the HTTP verb “POST” and URL path “/increment”.
    * The request entity is a JSON document representing the increment to apply to the counter.
    * The response entity is empty.
    */
  val increment: Endpoint[Increment, Unit] =
    endpoint(post(path / "increment", jsonRequest[Increment]()), emptyResponse())
  
  // Generically derive the JSON schema of our `Counter`
  // and `Increment` case classes defined thereafter
  implicit lazy val counterSchema: JsonSchema[Option[Counter]] = genericJsonSchema
  implicit lazy val incrementSchema: JsonSchema[Increment] = genericJsonSchema
  
}

case class Counter(value: Int)
case class Increment(step: Int)

import endpoints.openapi
import endpoints.openapi.model.{Info, OpenApi}

/**
  * Generates OpenAPI documentation for the endpoints described in the `CounterEndpoints` trait.
  */
object CounterDocumentation
  extends CounterEndpoints
    with openapi.Endpoints
    with openapi.JsonSchemaEntities {
  
  val api: OpenApi =
    openApi(
      Info(title = "API to manipulate a counter", version = "1.0.0")
    )(currentValue, increment)
  
}

import endpoints.akkahttp.server._

object CounterServer extends CounterEndpoints with OpenApiSchemas with JsonSchemaEntities {
  var counter = 0
  
  def docRoute: Route =
    endpoint(get(path / "documentation.json"), jsonResponse[OpenApi]())
      .implementedBy(_ => CounterDocumentation.api)
  
  def packagesRoute: Route =
    currentValue.implementedBy(_ => Some(Counter(counter)))
  
  def incRoute: Route =
    increment.implementedBy(inc => counter += inc.step)
}
```
In my project this results in
>Error:(36, 66) type mismatch;
 found   : CounterEndpoints.this.JsonSchema[shapeless.HNil]
 required: CounterEndpoints.this.JsonSchema[Option[solr.proxy.rest.endpoint.Counter]]
  implicit lazy val counterSchema: JsonSchema[Option[Counter]] = genericJsonSchema

Other than that I should be able to create circe codecs from algebra operations. It's going to take some time however, since the model contains ~120 classes, which is why I wanted to start with automatic derivation :)

**Comment by julienrf** [comment]
Indeed, we have no schema for top-level options. They can be present as fields, though:

~~~ scala
case class OptionalCounter(maybeCounter: Option[Int])
~~~

**Comment by julienrf** [comment]
Alternatively, you can just provide your own `JsonSchema[Option[A]]`.

**Comment by goboss** [comment]
I managed to get it working now. Thank you for your help! :+1:
