### ISSUE TITLE
QueryString values can not been transformed with xmap and xmapPartial

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#294]
We should:
- add an abstract defintion `implicit def queryStringPartialInvFunctor: PartialInvariantFunctor[QueryString]` in `endpoints.algebra.Urls`,
- implement it in all the interpreters,
- add a test for it in `endpoints.algebra.client.EndpointsTestSuite`,
- add a test for it in `endpoints.algebra.server.EndpointsTestSuite`,
- add an example in the documentation `endpoints.algebra.EndpointsDocs`.

For instance, the example could be (and it could also be used for tests):

~~~ scala
case class Location(longitude: Double, latitude: Double)

val locationQueryString: QueryString[Location] =
  (qs[Double]("lon") & qs[Double]("lat"))
    .xmap(
      { case (lon, lat) => Location(lon, lat) },
      location => (location.longitude, location.latitude)
    )
~~~

Another one, illustrating `xmapPartial`, could be the following:

~~~ scala
sealed trait BlogId
case class BlogUuid(uuid: UUID) extends BlogId
case class BlogSlug(slug: String) extends BlogId

val blogIdQueryString: QueryString[BlogId] =
  (qs[Option[UUID]]("uuid") & qs[Option[String]]("slug"))
    .xmapPartial {
      case (maybeUuid, maybeSlug) =>
        maybeUuid.map(BlogUuid).orElse(maybeSlug.map(BlogSlug))
    } {
      case BlogUuid(uuid) => (Some(uuid), None)
      case BlogSlug(slug) => (None, Some(slug))
    }
~~~

**Comment by fabianpage** [comment]
we are working on this.

**Comment by Swalkyn** [comment]
I am working on this issue
