### ISSUE TITLE
Syntax of xmap and xmapPartial are not consistent

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#296]
`xmap` takes two function parameters (e.g. `xmap(f, g)`), whereas `xmapPartial` has two parameter lists, taking a function each (e.g. `xmapPartial(f)(g)`).

We should use a similar syntax for both operations. I have a preference for using two parameter lists because it often helps with type inference, and because it avoids nesting braces in parens (ie, `xmap({ case (a, b) => e }, ...)` becomes `xmap { case (a, b) => e }(...)`)

**Comment by fabianpage** [comment]
we are working on that.
