### ISSUE TITLE
Support for universal json API for both request and response

### ISSUE THREAD

**Issue by Krever** [julienrf/endpoints#30]
As mentioned in #27 we can think about supporting something like:
```
endpoint(post(path / "foo", json[Foo]), json[Bar])
```

Creating issue to not forget about this, IMHO very good, idea.

**Comment by julienrf** [comment]
Note that while I would be super happy to have such a simple API, IMHO an important goal (that’s not visible when we read the above code example) is to make the user-facing API as type inference friendly as possible, and with type signatures as simple as possible.

**Comment by Krever** [comment]
Yes, completely agree. This ticket is for me(or someone else) just to remember to check if it is even possible(keeping API simplicity).

**Comment by julienrf** [comment]
I think that supporting this style would complicate the user-facing API too much (unless I’m wrong, we’d need an implicit parameter to indicate whether we are within a request or within a response).

I’m closing this issue but if someone finds a simple way to support this syntax, feel free to re-open it.
