### ISSUE TITLE
akkahttp.{server,client}.JsonSchemaEntities should not have a hard-coded dependency on circe

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#303]
The package name of these classes does not make it clear that they depend on circe. Furthermore, at the build level the dependency is marked as provided, meaning that users might get a runtime ClassNotFoundError if they don’t include the dependency.

~We should move the `endpoints.akkahttp.server.JsonSchemaEntities` trait to an `endpoints.akkahttp.server.circe` package, which would be defined in an `akkahttp-server-circe` sbt module (as we do with `play-server-circe`) with an explicit dependency on circe.~ And then do the same with `endpoints.akkahttp.client.JsonSchemaEntities`.

**Comment by fabianpage** [comment]
will work start work on that.

**Comment by fabianpage** [comment]
Unfortunately i didn't had yet a lot of time... My first try is at https://github.com/tegonal/endpoints/tree/303_json_schema_should_not_be_hard_dependend_on_circe

But there i get an error with the implicit resolution. Can you give me a hint here?

```
[error] endpoints/akka-http/server-circe/src/main/scala/endpoints/akkahttp/server/JsonSchemaEntities.scala:20: ambiguous implicit values:
[error]  both value StringCanBuildFrom in object Predef of type => scala.collection.generic.CanBuildFrom[String,Char,String]
[error]  and method $conforms in object Predef of type [A]=> A <:< A
[error]  match expected type T
[error]     Directives.entity[A](implicitly)
[error]                          ^
[error] endpoints/akka-http/server-circe/src/main/scala/endpoints/akkahttp/server/JsonSchemaEntities.scala:25: type mismatch;
[error]  found   : A
[error]  required: akka.http.scaladsl.marshalling.ToResponseMarshallable
[error]     Directives.complete(a)
[error]                         ^
[warn] /home/fabian/projects/endpoints/akka-http/server-circe/src/main/scala/endpoints/akkahttp/server/JsonSchemaEntities.scala:19: local method decoder in method jsonRequest is never used
[warn]     implicit def decoder: Decoder[A] = implicitly[JsonSchema[A]].decoder

```

**Comment by fabianpage** [comment]
The actual commit: https://github.com/tegonal/endpoints/commit/6948062105d920b04cee24b53cb0c68de2ceb869

**Comment by julienrf** [comment]
Isn’t it because you removed that import?

https://github.com/julienrf/endpoints/compare/master...tegonal:303_json_schema_should_not_be_hard_dependend_on_circe#diff-de2d1d678fa93749fd74082033817a90L4

**Comment by fabianpage** [comment]
Slowly with the lower temperatures my brain starts to work again. Can you have a look at: https://github.com/julienrf/endpoints/pull/321

**Comment by julienrf** [comment]
I’m re-opening the issue because we should still do the same for the *client* interpreters.

**Comment by fabianpage** [comment]
Ah i didn't think about the client...

**Comment by julienrf** [comment]
No worries! Thanks for having done the server part :) I should have broken this ticket into two tickets, anyways.

**Comment by fabianpage** [comment]
:+1:
