### ISSUE TITLE
Improve errors reported by servers

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#307]
Currently, malformed request get a 400 (Bad request) response status code and an empty response entity. This is fine as long as clients are *endpoints* derived clients, but ad-hoc clients or humans trying to play with an HTTP API served by *endpoints* will find it hard to understand the origin of the error.

Servers should provide meaningful error messages to clients. For instance, a missing query string parameter should be reported as such, an invalid segment value should be reported as such, an invalid JSON request should be reported as such, etc.

One challenge is that users of *endpoints* should keep control on the format used to report errors (in contrast with frameworks like Play, for instance, which decide to return an HTML page in case of error, even though the endpoint is supposed to return JSON content!).

A first step would be to define a data structure for error handling, for instance:

~~~ scala
sealed trait Validated[+A]
case class Invalid(errors: Seq[Throwable]) extends Validated[Nothing]
case class Valid[+A](value: A) extends Validated[A]
~~~

And replace all the places in the code where we use `Either[Throwable, A]` with `Validated[A]`. In some places (e.g. `QueryString`, `PartialInvariantFunctor`) we model decoding errors with `Option`. This should be replaced with `Validated` as well.

Then, errors should be reported to clients instead of sending an empty 400 HTTP response. We should define a method serializing an `Invalid` value into some “default” content type (e.g. `application/json`). Users could then override this method to change the format of error reporting.

**Comment by robstoll** [comment]
As an additional idea, I would base the "default" content type on the `Accept` header of the client. Ideally taking the weighting of the client into account (but maybe kick off without it).
