### ISSUE TITLE
Support documenting endpoints as “deprecated”

### ISSUE THREAD

**Issue by tdroxler** [julienrf/endpoints#345]
Since [OpenAPI 3.0,](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md) it's possible to deprecate endpoints/fields etc.

I suppose for then endpoints we could do something like: 
```scala
  def endpoint[A, B](
    request: Request[A],
    response: Response[B],
    summary: Documentation = None,
    description: Documentation = None,
    tags: List[String] = Nil,
    deprecated: Boolean = false,
  ): Endpoint[A, B]
```
For the fields I haven't thought about it yet

**Comment by julienrf** [comment]
Maybe we should group all documentation related information into a single parameter, instead of having `summary`, `description`, `tags` and now `deprecated`?

**Comment by tdroxler** [comment]
yep good idea
