### ISSUE TITLE
algebra.Urls is not mixing PartialInvariantFunctorSyntax

### ISSUE THREAD

**Issue by gmarti** [julienrf/endpoints#353]
We need to mix a trait in 0.10.1 to be able to use xmap in algebra.Urls : `trait Urls extends algebra.Urls with PartialInvariantFunctorSyntax`

And i think algegra.Urls should mix PartialInvariantFunctorSyntax and use it instead of : 
```
implicit def uuidQueryString: QueryStringParam[UUID] =
    queryStringParamPartialInvFunctor.xmapPartial(stringQueryString, (x: String) => Try(UUID.fromString(x)).toOption, _.toString)
```

We have afterwards` trait Requests extends Urls with Methods with PartialInvariantFunctorSyntax with SemigroupalSyntax` but we should be able to extends only Urls and go with it right ? withtout mixing some syntax sugar

**Comment by julienrf** [comment]
Fixed by #354
