### ISSUE TITLE
Rename package of server interpreters to “server” instead of “routing”

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#40]
Actually I already did the modification for the play-server interpreter (it is now in `endpoints.play.server` instead of `endpoints.play.routing`).
@Krever do you think that makes sense and that we should also rename the akka-http server’s package to `endpoints.akkahttp.server`?

**Comment by Krever** [comment]
Certainly! I was wondering why it is not server at the first place, but then I just forgot about that.

**Comment by julienrf** [comment]
Done :)
