### ISSUE TITLE
Evaluate gains from using ThoughtWorksInc/Constructor.scala

### ISSUE THREAD

**Issue by Krever** [julienrf/endpoints#43]
Our whole library is based on traits and mixing them. Maybe we can somehow utilize https://github.com/ThoughtWorksInc/Constructor.scala to improve tha API ? I don't have any particular idea in mind right now but maybe we can come up with something in the future.

**Comment by julienrf** [comment]
Thanks for pointing this out! That could be very useful to provide support for extensible syntax, indeed.

**Comment by julienrf** [comment]
I’m closing this issue since it is just an implementation suggestion.
