### ISSUE TITLE
Provide non-play jvm client interpreter

### ISSUE THREAD

**Issue by Krever** [julienrf/endpoints#45]
Currently we have only one jvm client interpreter, backed by Play Framework. There are two main problems with it:
- Play is still not avaiable for scala 2.12 and already not available for scala 2.10
- It is quite [hard](https://www.playframework.com/documentation/2.3.x/ScalaWS#Using-WSClient) to use it outside of play application

We may consider implementing another intepreter, backed with [scalaj/scalaj-http](https://github.com/scalaj/scalaj-http) or [hmil/RosHTTP](https://github.com/hmil/RosHTTP) (this one will give use scala.js interpreter for free as well).

I'm not 100% sure of this because we already have quite big number of interpreters, and without some generic automated tests the maintenance may become a lot of pain in the future.

**Comment by julienrf** [comment]
I think an akka-http client interpreter would make sense. People using an Akka based stack will be happy to have it.

**Comment by Krever** [comment]
Fixed by #46
