### ISSUE TITLE
Update documentation about the current state of interpreters

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#48]
We should try to keep the doumentation up to date with the current implementation state.

More specifically, [this page](http://julienrf.github.io/endpoints/interfaces-and-interpreters.html) should be updated to mention the new scalaj based client interpreter.

**Comment by Krever** [comment]
Hah, I was thinking about that and will definitely take care of that. I just wanted to wait for end result of #47 to put in docs as well.

**Comment by julienrf** [comment]
This has been fixed by #49.
