### ISSUE TITLE
Simplify directories layout and build definition

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#50]
The number of directories is huge and refrains me from adding new modules. Also, the build definition is huge and hardly readable.

We might eventually split this project into several repositories. However this would come at a cost (we would have to re-publish the core modules each time we change them before being able to see the changes in the leaves).

Alternatively, we could group together the modules and use several `build.sbt` definitions. Here is a possible layout:

~~~
- algebras
  - algebra
  - algebra-circe
- play
  - server
  - client
  - circe
  - client-circe
  - server-circe
- scalaj
  - client
  - client-circe
- akka-http
  - server
  - server-circe
- openapi
  - openapi
  - openapi-circe
- examples
  - basic
  - cqrs
  - overview
- manual
- testsuite
~~~

**Comment by Krever** [comment]
I like the idea of grouping, as it keeps everything in one repository and reduce number of directories over twice.

**Comment by julienrf** [comment]
I started working on this issue (I forgot to do a branch and directly pushed to master…). However I wasn’t able to split the build files. I would like to have one build.sbt file per directory (e.g. `algebras/build.sbt`). The problem is that I can not, from `play/build.sbt` refer to a module defined in `algebras/build.sbt`.

Maybe the only solution would be to have several build files (for clarity) but to put all of them in the `project/` directory (that would be .scala files, then).

**Comment by Krever** [comment]
Have you tried to use `LocalProject` to reference the modules ?

**Comment by julienrf** [comment]
It seems to be working with `LocalProject`, thanks for the tip!

**Comment by Krever** [comment]
Great work!
