### ISSUE TITLE
Support OpenAPI's `title` and `description`

### ISSUE THREAD

**Issue by harpocrates** [julienrf/endpoints#500]
In OpenAPI, one can attach a `title` and `description` to any schema. It would be useful if `endpoints` also allowed these to be specified for any schema. Note about `title`: unlike the "name" that `endpoints` allows users to customize (see `namedTagged`, `namedRecord`, etc.), `title` does not need to be a valid uri, which means it can have spaces and interesting characters in it.

AFAICT, this would be a pretty straightforward change. At a glance, probably not much more than:

  - [ ] add `title: Option[String]` and `description: Option[String]` fields to every variant of `DocumentedJsonSchema` (and to the trait itself, like `example: Option[ujson.Value]`)
  - [ ] add a `title: Option[String]` field to every variant of `openapi.Schema`
  - [ ] update `OpenApi.schemaJson` to properly propagate these fields into the generated OpenAPI schemas
  - [ ] add `withTitleJsonSchema[A](schema: JsonSchema[A], title: String): JsonSchema[A]` and `withDescriptionJsonSchema[A](schema: JsonSchema[A], description: String): JsonSchema[A]`, and implement it for all relevant interpreters

Is this is a feature `endpoints` would like to support and is the plan I've laid out above reasonable? If so, I'd be happy to open a PR for this.

PS. Thank you for this great project. The extensible trait-based approach is really nice!

**Comment by julienrf** [comment]
Hey @harpocrates thanks for the detailed issue! Yes, this is definitely something I would like to support :) The plan you propose is perfect, you clearly identified all the action points.
