### ISSUE TITLE
Support un-naming a schema

### ISSUE THREAD

**Issue by harpocrates** [julienrf/endpoints#501]
When making a `Record`, `Tagged`, or `Enum`, we can name it with `namedRecord`, `namedTagged`, and `namedEnum` (or the corresponding methods on the implicit classes). Naming a schema means that it will get its own section in the `schemas` part of the generated OpenAPI docs. Furthermore, schemas derived via `genericRecord`, `genericTagged`, and `genericJsonSchema` are _always_ named.

Having named types is sometimes undesirable (especially when a derived schema is used as a part of a larger schema). It would be nice to support _un-naming_ a schema:

```scala
trait JsonSchemas {

  /** Removes any name from the record JSON schema */
  def unnamedRecord[A](schema: Record[A]): Record[A]

  /** Removes any name from the tagged JSON schema */
  def unnamedTagged[A](schema: Tagged[A]): Tagged[A]

  /** Removes any name from the enum JSON schema */
  def unnamedEnum[A](schema: Enum[A]): Enum[A]

}
```

This would effectively allow users to control schema inlining in the generated documentation.

Thoughts? I'm trying to figure out how to make some schemas more palatable, but I suspect I'm missing some other constraints here...

**Comment by julienrf** [comment]
The motivation is to undo what’s done in the generic JSON schema derivation process?

Maybe we can achieve this by changing the signature of [GenericSchemaName](http://julienrf.github.io/endpoints/api/endpoints/generic/JsonSchemas$GenericSchemaNames$GenericSchemaName.html) to return an `Option[String]` instead of a `String`, so that you could add an implicit rule that would always provide an empty name

**Comment by harpocrates** [comment]
> The motivation is to undo what’s done in the generic JSON schema derivation process?

Yeah, that was the idea. Framing the problem as such, it does make more sense to patch `GenericSchemaName`. I'll see if that is enough for our purposes.

**Comment by julienrf** [comment]
In the meantime, what you can currently do is to override the existing [recordGeneric and taggedGeneric methods](https://github.com/julienrf/endpoints/blob/aef9ec843cf9fc354f6c392bb74fbd9f5afa3abc/json-schema/json-schema-generic/src/main/scala/endpoints/generic/JsonSchemas.scala#L178-L201) to do exactly the same thing but without the `.named` part.
