### ISSUE TITLE
`withExampleJsonSchema` loses schema specificity

### ISSUE THREAD

**Issue by harpocrates** [julienrf/endpoints#505]
If I have a `Record[A]`, there is no way to attach an example to this record and still have a `Record[A]` afterwards. The reason for this is that the type of `withExampleJsonSchema` only talks about `JsonSchema`:

```scala
case class Foo(i: Int)
val fooSchema: Record[Foo] = genericRecord[Foo].withExample(Foo(4)) // compile error
```

This issue also holds for `withDescriptionJsonSchema` and `withTitleJsonSchema`.

**Comment by julienrf** [comment]
I didn’t find a better solution for this than defining each operation also as a method of `Record`, `Tagged`, and `Enum`, like this is done with the `named` operation, but this leads to a lot of code duplication/boilerplate.

An alternative (that I didn’t try) could be to encode the “self” type of a `JsonSchema` somewhere and to return that type:

~~~ scala
type JsonSchema[A] <: { type Self[A] <: JsonSchema[A] }

type Tagged[A] <: { type Self[A] <: Tagged[A] }
// etc.

def withDescriptionJsonSchema[A](description: String, schema: JsonSchema[A]): schema.Self[A]
~~~

**Comment by harpocrates** [comment]
Yeah. I played around with `def withDescriptionJsonSchema[F[X] <: JsonSchema[X], A](description: String, schema: F[A]): F[A]`, but that signature is a bit too strong to be implementable.

I have another patch I'm nearly done that went the longer way you describe: defining seperate methods for each of `Record`, `Tagged`, and `Enum`. To reduce some boilerplate, the implicit ops methods are put into a common trait that `JsonSchemaOps`/`EnumOps`/`RecordOps`/`TaggedOps` all extend. If nothing else, this saves us from duplicating docstrings. 😄 

```scala
sealed trait DocOps[A] {
  type Repr[X] <: JsonSchema[X]

  def withExample(example: A): Repr[A]
  def withDescription(description: String): Repr[A]
  def withTitle(title: String): Repr[A]
}
```

FYI: the real motivation for these operations is so that we can use annotations to specify descriptions, titles, and maybe examples in generic derivation.

**Comment by julienrf** [comment]
> FYI: the real motivation for these operations is so that we can use annotations to specify descriptions, titles, and maybe examples in generic derivation.

Yes, I understand. That was the reason for duplicating the `named` operation everywhere.
