### ISSUE TITLE
Using `orElse` + `xmap` is too verbose

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#515]
By using `orElse` between alternative tagged schemas we can model schemas for sealed traits. However, the resulting schema has type `Tagged[Either[Bar, Baz]]]` that we have to eventually turn into a single `JsonSchema[Foo]` (assuming that `Foo` is a super type of `Bar` and `Baz`) with `xmap`:

~~~ scala
val schemaFoo =
  schemaBar.tagged("Bar").orElse(schemaBaz.tagged("Baz"))
    .xmap[Foo] {
      case Left(bar)  => bar
      case Right(baz) => baz
    } {
      case bar: Bar => Left(bar)
      case baz: Baz => Right(baz)
    }
~~~

The call to `xmap` is a bit cumbersome. This could be improved by introducing an operation `orElseMerge:

~~~ scala
def orElseMergeTagged[A: ClassTag <: C, B: ClassTag <: C, C](taggedA: Tagged[A], taggedB: Tagged[B]): Tagged[C]
~~~

This operation could be implemented in terms of `orElse` and `xmap`, and would use the `ClassTag`s to implement the runtime-type checks.

Then, the above example would look like:

~~~ scala
val schemaFoo =
  schemaBar.tagged("Bar").orElseMerge(schemaBaz.tagged("Baz"))
~~~

This operation should be presented in the [Sum types](http://julienrf.github.io/endpoints/algebras/json-schemas.html#sum-types-sealed-traits-) section of the documentation page on JSON schemas ([source](https://github.com/julienrf/endpoints/blob/master/documentation/manual/src/paradox/algebras/json-schemas.md)). We should warn that since it relies on `ClassTag`s, it only works if the two alternatives have distinct erased types.

**Comment by harpocrates** [comment]
Although I still want this function, I think it is worth stating the the semantics more explicitly. `orElseMerge` makes it sound like this is a variant of `orElse`, meaning that it is making an unambiguous choice. However, the type signature means that sometimes the choice will have to be ambiguous.

What happens if I pick `A`, `B`, and `C` to be equal? What about if `A` or `B` is a subtype of the other? Note that the very last case is not an edge case: it is the _usual_ case when building up a large co-product.

**Comment by julienrf** [comment]
> What happens if I pick `A`, `B`, and `C` to be equal?

`A` will always win. But we already have a similar issue with `orFallbackTo`.
However, this case should not happen much.

> What about if `A` or `B` is a subtype of the other?

This should work as long as `A` and `B` have distinct types after erasure. We should add a test for this, definitely.

**Comment by bmeesters** [comment]
I will start on this ticket now
