### ISSUE TITLE
Variant of `xmapPartial` that takes a `Codec` argument

### ISSUE THREAD

**Issue by harpocrates** [julienrf/endpoints#528]
Might be useful to have an `xmapPartialAlong` method on `PartialInvariantFunctorSyntax` that takes just a `Codec` as an argument: `fa.xmapPartialAlong(codec)`. The name `xmapPartialAlong` is not very good though.

**Comment by julienrf** [comment]
`xmapPartialWithCodec`?

**Comment by harpocrates** [comment]
I'll open a PR. I don't see any tests directed at `xmapPartial` - should I just tack something on to `EndpointsTestSuite` (maybe re-using the same `Codec[String, Something]` to `xmapPartialAlong` both a segment and a text response)?

**Comment by julienrf** [comment]
Not on `EndpointsTestSuite`, I would rather create a self-contained test [here](https://github.com/julienrf/endpoints/tree/master/algebras/algebra/src/test/scala/endpoints).
