### ISSUE TITLE
Akka HTTP client doesn't properly encode segments with spaces

### ISSUE THREAD

**Issue by mleclercq** [julienrf/endpoints#574]
If a URL segment contains a space, it is encoded as `+` instead of `%20` (`+` is OK for query-string, but in the path of the URL, `%20` should be used).

I did the following, using Akka `Uri` to workaround the issue:

```scala
    override implicit lazy val stringSegment: Segment[String] = (s: String) =>
      Uri.Path.Segment(s, Uri.Path.Empty).toString()
```

**Comment by julienrf** [comment]
Good catch! Would you be interested in contributing a fix? You need to fix the Akka-HTTP interpreter and also add tests [here](https://github.com/julienrf/endpoints/blob/e52dbb17da69ac5488201b860382abfc1369eb24/algebras/algebra/src/test/scala/endpoints/algebra/client/EndpointsTestSuite.scala#L318-L333)
