### ISSUE TITLE
Support for Http headers

### ISSUE THREAD

**Issue by Fristi** [julienrf/endpoints#59]
The endpoint library only supports the basic authentication header. In itinere we've build in request headers parsing: https://github.com/Fristi/endpoints-proto/blob/master/algebra/src/main/scala/itinere/Algebra.scala#L119

We could easily also do this for response headers. I'm also thinking to introduce a StringCodec which allows you to parse Int, Double, UUID and so on from a String as well you could encode and decode Base64, JSON, etc from that. This would make it easy to implement basic authenication.

Also you can encode/decode data to/from headers

**Comment by Krever** [comment]
Fixed by #90 . We support only string request headers for now, but with `xmap` we can at least map them to any other type. I will close it for now, as I believe responses requires more love in general, not only in scope of headers and we trakc it in sope of #42 .
