### ISSUE TITLE
Add support for streamed entities

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#6]
Streamed entities is useful for long polling, server-sent events, websockets, and for serving large entities.

Consider using [monix](monix.io) to give a consistent programming experience on server and client sides.

**Comment by Fristi** [comment]
Great idea.

I've played with this idea as well (in a project called nuntius, repo is offline (but I can get it back)). I had a Monifu server + scala.js Monifu client running. I didn't apply any back-pressure in the protocol, but the client-server communication was multiplexed across one connection. 

WDYT about multiplexing and back-pressure ?

**Comment by julienrf** [comment]
Hi,

I don’t think multiplexing should be the default: users should be able to define the endpoints they want. Multiplexing could always be added on top of an endpoint definition.

Back-pressure should be supported, yes.

**Comment by julienrf** [comment]
I’ve pushed a basic implementation of endpoints responding with server-sent events in the [`streaming` branch](dbcbdf3f48e1a98252d0649be2ed85c3a4c6129d), in case someone wants to use it as a starting point or wants to discuss it…
