### ISSUE TITLE
Compatibility check of endpoints

### ISSUE THREAD

**Issue by Fristi** [julienrf/endpoints#61]
We could emit a tree which contains schema's of types and also endpoint information. 

By doing that we have a representation how a API is for a certain moment in time. This could be stored in some data store. Modifying the endpoint algebra could trigger a error to tell the implementor of the API that the modifications will be breaking. 

Very abstract idea, yet you may have more idea's, please fire :-)

**Comment by Krever** [comment]
This sounds super interesting, mostly because people ten to break API by accident and there is no good way to check it automatically in standard frameworks.

What it would require is just a simple interpreter that will put all data in case classes and then set of rules to specify if two trees are compatible. 

The first part is trivial but I wonder what would be the rules...

**Comment by Krever** [comment]
I was thinking about this recently and the biggest obstacle seems to be storage of the previous version. 
One of the solutions may be something like this:

```scala
class MyCompatibilitySpec extends WordSpec { //standard test suite

    val compatibilityCheck = new MyApi extends CompatibilityCheckInterpreter

    compatibilityCheck.test("hashOfPreviousApi")

}
```
So the interpreter will expose a method that checks current implementation with some hash/base64 encoded tree. In case of compatibility break, the test will fail. In case of newly added methods/parameters test would also break but with a comment telling the user to update the hash(and printing the new one obviously).

**Comment by Fristi** [comment]
Confluent does such a thing with a schema-registry (for entity schemas).
Pact does it with a Pact broker, we could provide a same thing for it.
Currently working on https://github.com/vectos/jason, which has schema compat checks for entity types. It's not hard, but it's kind of raw code and could be improved upon.

**Comment by krzemin** [comment]
Perhaps [openapi-diff](https://github.com/quen2404/openapi-diff) might be used for detecting breaking changes. As long as we produce openapi documentation, it seems it may be easily plugged into development pipeline externally. However I haven't tried this yet.

**Comment by Fristi** [comment]
No shared excitement for this feature and I don't have a need for it as well. It was just a wild idea, closing it for now.
