### ISSUE TITLE
Use docless for swagger/json-schema inference

### ISSUE THREAD

**Issue by Krever** [julienrf/endpoints#75]
We may want to use what was developed in https://github.com/timeoutdigital/docless instead of maintaining our own implementation. It looks like quite young project but may be worth considering in couple of month's.

**Comment by julienrf** [comment]
Nice project, indeed!

**Comment by guersam** [comment]
Although not providing swagger support directly, [xenomorph](https://github.com/nuttycom/xenomorph) seems really interesting too. It brings great extensibility to a single schema.

**Comment by Fristi** [comment]
I tried docless, yet I favored having it on my own (there were some types overcomplicated and if I recall correctly it was not immediately compatible with the algebra)

**Comment by julienrf** [comment]
I’m closing this issue since we have no actual problems with our current implementation of JSON schema. We can re-open it if needed.
