### ISSUE TITLE
Make it possible to generate links from the Scala.js Endpoint interpreter

### ISSUE THREAD

**Issue by julienrf** [julienrf/endpoints#84]
Currently the concrete type for `Endpoint[A, B]` in the `xhr.Endpoints` interpreter is `A => Result[B]`. Consequently, from the client interpreter it’s only possible to invoke an endpoint, but not to generate a link to it.

We should change the `Endpoint[A, B]` type to the following:

~~~ scala
class Endpoint[A, B] {
  def apply(a A): Result[B]
  def href(a: A): String
}
~~~

Note that this is going to be useful for `GET` endpoints only because for `POST` endpoints the `A` type also contains the request entity…

**Comment by Fristi** [comment]
In the interpreter can't you just ignore `B`? 

```
trait LinkEndpoint[A] {
   type Result[B] = String

   def apply(value: A): Result[B]
}
```

**Comment by julienrf** [comment]
Yes we can do that but I thought it could be useful to have both the ability to invoke the endpoint and the ability to build a URL.
